<?php

namespace JMose\CommandSchedulerBundle\Entity\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * ExecutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExecutionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find all executions fo a given command
     *
     * @param integer $commandId
     * @return ArrayCollection
     */
    public function findCommandExecutions($commandId)
    {
        $result = new ArrayCollection();
        $logs = $this->findBy(array('command' => $commandId), array('id' => 'ASC'));

        // convert array to ArrayCollection
        foreach($logs as $log) {
            $result->add($log);
        }

        return $result;
    }
}
