<?php

namespace JMose\CommandSchedulerBundle\Entity;

/**
 * UserHostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHostRepository extends \Doctrine\ORM\EntityRepository
{
}
